import { TWO_PI } from '../math/constants.js';
import { clamp, wrapUnit } from '../math/util.js';

export type Waveform = 'sine' | 'triangle' | 'square' | 'saw' | 'harmonic';

export const WAVEFORMS: readonly Waveform[] = ['sine', 'triangle', 'square', 'saw', 'harmonic'];

/**
 * Phase accumulator.
 *
 * Phase is stored normalised (0..1) rather than in radians: it keeps precision
 * over multi-hour sessions (a radian accumulator loses mantissa bits as it
 * grows) and makes the wrap a single subtraction. Frequency changes never reset
 * phase — that is what keeps sweeps and automation click-free (§25).
 */
export class Phasor {
  private phase: number;

  constructor(
    private sampleRate: number,
    initialPhase = 0,
  ) {
    this.phase = wrapUnit(initialPhase);
  }

  setSampleRate(sampleRate: number): void {
    this.sampleRate = sampleRate;
  }

  /** Current phase in the normalised 0..1 domain. */
  get value(): number {
    return this.phase;
  }

  /** Current phase in radians, for callers that need the trigonometric form. */
  get radians(): number {
    return this.phase * TWO_PI;
  }

  /**
   * Explicitly re-aligns phase. Only called at session start or when the user
   * asks for a hard reset — never during automation.
   */
  resetPhase(normalisedPhase = 0): void {
    this.phase = wrapUnit(normalisedPhase);
  }

  /** Advances one sample at `frequency` Hz and returns the phase *before* the step. */
  advance(frequency: number): number {
    const current = this.phase;
    this.phase += frequency / this.sampleRate;
    if (this.phase >= 1) this.phase -= Math.floor(this.phase);
    else if (this.phase < 0) this.phase -= Math.floor(this.phase);
    return current;
  }

  /** Phase increment per sample at `frequency` Hz. */
  increment(frequency: number): number {
    return frequency / this.sampleRate;
  }
}

/**
 * PolyBLEP correction. Square and saw are generated by their naive formula and
 * then corrected around the discontinuity, which removes most of the aliasing
 * without the cost of wavetables. Sine and triangle need no correction.
 */
function polyBlep(t: number, dt: number): number {
  if (dt <= 0) return 0;
  if (t < dt) {
    const x = t / dt;
    return x + x - x * x - 1;
  }
  if (t > 1 - dt) {
    const x = (t - 1) / dt;
    return x * x + x + x + 1;
  }
  return 0;
}

/** Evaluates a waveform at normalised phase `t` with per-sample increment `dt`. */
export function waveformSample(kind: Waveform, t: number, dt: number): number {
  switch (kind) {
    case 'sine':
      return Math.sin(TWO_PI * t);
    case 'triangle': {
      // Integrating a band-limited square would be more exact; for the carrier
      // frequencies this instrument uses (20–1500 Hz) the naive triangle's
      // aliasing sits below -80 dBFS, which measures clean.
      const x = t < 0.5 ? 4 * t - 1 : 3 - 4 * t;
      return x;
    }
    case 'square': {
      let value = t < 0.5 ? 1 : -1;
      value += polyBlep(t, dt);
      value -= polyBlep(wrapUnit(t + 0.5), dt);
      return value;
    }
    case 'saw': {
      let value = 2 * t - 1;
      value -= polyBlep(t, dt);
      return value;
    }
    case 'harmonic':
      // Harmonic mixtures are rendered by HarmonicOscillator, which sums
      // individual sine partials; a bare 'harmonic' falls back to its fundamental.
      return Math.sin(TWO_PI * t);
    default:
      return Math.sin(TWO_PI * t);
  }
}

/** A single phase-continuous oscillator with a selectable waveform. */
export class Oscillator {
  private readonly phasor: Phasor;

  constructor(
    private sampleRate: number,
    public waveform: Waveform = 'sine',
    initialPhase = 0,
  ) {
    this.phasor = new Phasor(sampleRate, initialPhase);
  }

  setSampleRate(sampleRate: number): void {
    this.sampleRate = sampleRate;
    this.phasor.setSampleRate(sampleRate);
  }

  resetPhase(normalisedPhase = 0): void {
    this.phasor.resetPhase(normalisedPhase);
  }

  get phase(): number {
    return this.phasor.value;
  }

  /** Renders one sample at `frequency` Hz. `phaseOffset` is in turns (0..1). */
  next(frequency: number, phaseOffset = 0): number {
    const dt = this.phasor.increment(frequency);
    const t = this.phasor.advance(frequency);
    return waveformSample(this.waveform, phaseOffset === 0 ? t : wrapUnit(t + phaseOffset), dt);
  }
}

export interface HarmonicPartial {
  /** Integer or fractional multiple of the fundamental. */
  multiple: number;
  /** Linear amplitude, 0..1. */
  amplitude: number;
  /** Phase offset in turns, 0..1. */
  phase?: number;
}

/**
 * Additive harmonic stack sharing one fundamental phase accumulator, so every
 * partial stays locked to the fundamental across frequency automation.
 * Partials above Nyquist are muted rather than allowed to fold back.
 */
export class HarmonicOscillator {
  private readonly phasor: Phasor;

  constructor(
    private sampleRate: number,
    public partials: HarmonicPartial[] = [{ multiple: 1, amplitude: 1 }],
    initialPhase = 0,
  ) {
    this.phasor = new Phasor(sampleRate, initialPhase);
  }

  setSampleRate(sampleRate: number): void {
    this.sampleRate = sampleRate;
    this.phasor.setSampleRate(sampleRate);
  }

  resetPhase(normalisedPhase = 0): void {
    this.phasor.resetPhase(normalisedPhase);
  }

  /** Sum of all audible partials, normalised so the stack cannot exceed unity. */
  next(fundamental: number): number {
    const t = this.phasor.advance(fundamental);
    const nyquist = this.sampleRate * 0.5;
    let sum = 0;
    let norm = 0;
    for (let i = 0; i < this.partials.length; i++) {
      const partial = this.partials[i];
      const frequency = fundamental * partial.multiple;
      if (frequency >= nyquist || partial.amplitude <= 0) continue;
      const phase = wrapUnit(t * partial.multiple + (partial.phase ?? 0));
      sum += Math.sin(TWO_PI * phase) * partial.amplitude;
      norm += partial.amplitude;
    }
    return norm > 1 ? sum / norm : sum;
  }

  /** Peak-normalisation divisor for the current partial set. */
  get normalisation(): number {
    let norm = 0;
    for (const partial of this.partials) norm += Math.max(0, partial.amplitude);
    return norm > 1 ? norm : 1;
  }
}

/**
 * Isochronic / AM modulation envelope shapes. All are defined on normalised
 * phase and return 0..1, so a depth of 1 fully gates the carrier.
 */
export type EnvelopeShape = 'sine' | 'square' | 'softSquare' | 'triangle' | 'trapezoid';

export const ENVELOPE_SHAPES: readonly EnvelopeShape[] = [
  'sine',
  'softSquare',
  'square',
  'triangle',
  'trapezoid',
];

export interface PulseEnvelopeOptions {
  shape: EnvelopeShape;
  /** Fraction of the period the pulse is "on", 0.01..0.99. */
  dutyCycle: number;
  /** Rise time as a fraction of the on-period, 0..0.5. */
  attack: number;
  /** Fall time as a fraction of the on-period, 0..0.5. */
  release: number;
}

/**
 * Evaluates a pulse envelope at normalised phase `t`.
 *
 * `square` is the only shape with true discontinuities; Lab Mode warns before
 * allowing it (§27) because the edges produce broadband clicks by definition.
 * `softSquare` is the same gate with cosine attack/release ramps, which is the
 * default for isochronic stimulation.
 */
export function pulseEnvelope(t: number, options: PulseEnvelopeOptions): number {
  const duty = clamp(options.dutyCycle, 0.01, 0.99);
  if (t >= duty) return 0;
  const local = t / duty;

  switch (options.shape) {
    case 'square':
      return 1;
    case 'sine':
      // Raised cosine over the on-period: continuous value and slope at both edges.
      return 0.5 * (1 - Math.cos(TWO_PI * local));
    case 'triangle':
      return local < 0.5 ? local * 2 : (1 - local) * 2;
    case 'trapezoid':
    case 'softSquare': {
      const attack = clamp(options.attack, 0, 0.5);
      const release = clamp(options.release, 0, 0.5);
      if (attack > 0 && local < attack) {
        const x = local / attack;
        return options.shape === 'softSquare' ? 0.5 * (1 - Math.cos(Math.PI * x)) : x;
      }
      if (release > 0 && local > 1 - release) {
        const x = (1 - local) / release;
        return options.shape === 'softSquare' ? 0.5 * (1 - Math.cos(Math.PI * x)) : x;
      }
      return 1;
    }
    default:
      return 1;
  }
}
