"""Canonical schema for the organic audio asset manifest.

This module is the contract. The analysis code, the override merge, the
validator, the report and the generated TypeScript types are all derived from
what is declared here, so there is exactly one definition of what an asset
record is (§25: no duplicate competing schemas).

Three version numbers travel with every manifest, because they answer different
questions and move independently (§33):

  ``ANALYSIS_VERSION``   what the measuring code does. Bumping it invalidates
                         the analysis cache and forces every asset to be
                         re-measured, so it must change whenever a number this
                         pipeline computes would come out differently.
  ``SCHEMA_VERSION``     the shape of the record. A consumer that understands
                         schema 1 can refuse a schema 2 manifest outright
                         rather than reading fields that have moved.
  ``LIBRARY_VERSION``    the content of the sample library itself, which is a
                         curatorial fact rather than a technical one (§34).
                         Protocol DNA will reference it, so it is declared here
                         and carried through rather than derived.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

ANALYSIS_VERSION = "1.7.0"
SCHEMA_VERSION = 1
LIBRARY_VERSION = "0.1.0"

MANIFEST_HEADER = "AUTO-GENERATED BY tools/audio_pipeline — DO NOT EDIT DIRECTLY."

# ---------------------------------------------------------------------------
# Enumerations
#
# Every closed set the manifest can contain is declared here so the validator,
# the classifier and the emitted TypeScript union types cannot drift apart.
# ---------------------------------------------------------------------------

INSTRUMENTS = (
    "SINGING_BOWL",
    "BELL",
    "CHIME",
    "TUNING_FORK",
    "KALIMBA",
    "TEXTURE",
    "DRONE",
    "AMBIENT",
    "UNKNOWN",
)

DURATION_CLASSES = ("MICRO", "SHORT", "MEDIUM", "LONG", "EXTENDED")

TONALITY = ("TONAL", "PARTIALLY_TONAL", "INHARMONIC", "ATONAL", "UNKNOWN")

ROLES = (
    "ACCENT",
    "TRANSITION",
    "DETAIL",
    "BELL_STRIKE",
    "CHIME_STRIKE",
    "FORK_EVENT",
    "FOREGROUND_GESTURE",
    "RESONANT_HIT",
    "PHRASE",
    "SECONDARY_LAYER",
    "PRIMARY_BOWL",
    "LONG_RESONANCE",
    "MAJOR_EVENT",
    "BED",
    "EXTENDED_TEXTURE",
    "LONG_PERFORMANCE",
)

CHARACTER_TAGS = (
    "deep", "warm", "bright", "airy", "dark", "gentle", "strong", "metallic",
    "shimmering", "smooth", "rough", "low", "mid", "high",
    "short_decay", "medium_decay", "long_decay",
    "tonal", "inharmonic", "percussive", "sustained",
)

PITCH_CLASSES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")

# Formats libsndfile decodes without help. M4A/AAC need ffmpeg, which the
# pipeline treats as optional and reports as a warning rather than a failure.
NATIVE_EXTENSIONS = (".wav", ".wave", ".aif", ".aiff", ".aifc", ".flac", ".ogg", ".mp3", ".w64", ".caf")
FFMPEG_EXTENSIONS = (".m4a", ".aac", ".mp4")
SUPPORTED_EXTENSIONS = NATIVE_EXTENSIONS + FFMPEG_EXTENSIONS


@dataclass(frozen=True)
class DurationBand:
    """One duration class and the range that puts an asset in it.

    Bounds are seconds, lower-inclusive and upper-exclusive, so an asset of
    exactly 2.0 s lands in SHORT rather than in both or neither.
    """

    name: str
    min_seconds: float
    max_seconds: float | None


# §9's suggested defaults. Configurable: `config.py` can replace the table, and
# the exact duration is always stored alongside the class so no consumer is ever
# forced to work from the bucket alone.
DEFAULT_DURATION_BANDS: tuple[DurationBand, ...] = (
    DurationBand("MICRO", 0.0, 2.0),
    DurationBand("SHORT", 2.0, 6.0),
    DurationBand("MEDIUM", 6.0, 20.0),
    DurationBand("LONG", 20.0, 60.0),
    DurationBand("EXTENDED", 60.0, None),
)


def duration_class(seconds: float, bands: tuple[DurationBand, ...] = DEFAULT_DURATION_BANDS) -> str:
    for band in bands:
        if seconds >= band.min_seconds and (band.max_seconds is None or seconds < band.max_seconds):
            return band.name
    return bands[-1].name


# ---------------------------------------------------------------------------
# Record shape
# ---------------------------------------------------------------------------

# Every field, its JSON type, and whether it may be null. `None` in the type
# position means "any JSON value" and is used only for lists whose element shape
# is checked separately. This table drives both validation and TypeScript
# emission, so a field cannot be added to one without the other.
FIELD_SPEC: dict[str, dict[str, tuple[str, bool]]] = {
    "source": {
        "filename": ("string", False),
        "relativePath": ("string", False),
        "contentHash": ("string", False),
        "format": ("string", False),
        "bytes": ("integer", False),
    },
    "audio": {
        "durationSeconds": ("number", False),
        "sampleRate": ("integer", False),
        "channels": ("integer", False),
        "bitDepth": ("integer", True),
        "frameCount": ("integer", False),
    },
    "levels": {
        "peakDbFS": ("number", True),
        "truePeakDbFS": ("number", True),
        "rmsDbFS": ("number", True),
        "integratedLufs": ("number", True),
        "recommendedGainDb": ("number", True),
    },
    "timing": {
        "leadingSilenceSeconds": ("number", True),
        "trailingSilenceSeconds": ("number", True),
        "recommendedStartOffset": ("number", True),
        "recommendedEndOffset": ("number", True),
    },
    "spectral": {
        "fundamentalHz": ("number", True),
        "pitchConfidence": ("number", True),
        "note": ("string", True),
        "pitchClass": ("string", True),
        # Where the note came from. `measured` means the spectrum corroborated
        # it; `filename` means the library labelled it and the audio could not
        # confirm or deny. Never blank when a note is present: a consumer has to
        # be able to tell an analysis from a vendor's label.
        "noteSource": ("string", True),
        "tonality": ("string", False),
        "spectralCentroidHz": ("number", True),
        "spectralRolloffHz": ("number", True),
        "brightness": ("number", True),
        "transientStrength": ("number", True),
        "decaySeconds": ("number", True),
    },
    "classification": {
        "instrument": ("string", False),
        "durationClass": ("string", False),
    },
    "runtime": {
        "streamingRecommended": ("boolean", False),
        "preloadRecommended": ("boolean", False),
        "loopable": ("boolean", False),
        "maxRecommendedVoices": ("integer", False),
    },
    "review": {
        "approved": ("boolean", False),
        "manualOverride": ("boolean", False),
        "notes": ("string", True),
    },
}

# Sections whose contents are lists rather than scalar fields.
LIST_FIELDS = {
    "classification": ("recommendedRoles", "characterTags"),
    "spectral": ("resonantPeaksHz",),
}


@dataclass
class ValidationIssue:
    """One problem found by the validator.

    `fatal` decides whether preprocessing fails or merely warns (§27). The
    message is written for a person reading a terminal, not for a log parser
    (§51): it names the asset, the field and what would have to be true.
    """

    fatal: bool
    assetId: str | None
    message: str

    def render(self) -> str:
        where = f"{self.assetId}: " if self.assetId else ""
        return f"{'ERROR' if self.fatal else 'warning'}  {where}{self.message}"


@dataclass
class Asset:
    """One analysed asset, in the shape the manifest serialises."""

    assetId: str
    label: str
    source: dict[str, Any] = field(default_factory=dict)
    audio: dict[str, Any] = field(default_factory=dict)
    levels: dict[str, Any] = field(default_factory=dict)
    timing: dict[str, Any] = field(default_factory=dict)
    spectral: dict[str, Any] = field(default_factory=dict)
    classification: dict[str, Any] = field(default_factory=dict)
    runtime: dict[str, Any] = field(default_factory=dict)
    review: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        return {
            "assetId": self.assetId,
            "label": self.label,
            "source": self.source,
            "audio": self.audio,
            "levels": self.levels,
            "timing": self.timing,
            "spectral": self.spectral,
            "classification": self.classification,
            "runtime": self.runtime,
            "review": self.review,
        }
