"""Canonical schema for the organic audio asset manifest.

This module is the contract. The analysis code, the override merge, the
validator, the report and the generated TypeScript types are all derived from
what is declared here, so there is exactly one definition of what an asset
record is (§25: no duplicate competing schemas).

Three version numbers travel with every manifest, because they answer different
questions and move independently (§33):

  ``ANALYSIS_VERSION``   what the measuring code does. Bumping it invalidates
                         the analysis cache and forces every asset to be
                         re-measured, so it must change whenever a number this
                         pipeline computes would come out differently.
  ``SCHEMA_VERSION``     the shape of the record. A consumer that understands
                         schema 1 can refuse a schema 2 manifest outright
                         rather than reading fields that have moved.
  ``LIBRARY_VERSION``    the content of the sample library itself, which is a
                         curatorial fact rather than a technical one (§34).
                         Protocol DNA will reference it, so it is declared here
                         and carried through rather than derived.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

ANALYSIS_VERSION = "1.7.0"
SCHEMA_VERSION = 1
LIBRARY_VERSION = "0.1.0"

MANIFEST_HEADER = "AUTO-GENERATED BY tools/audio_pipeline — DO NOT EDIT DIRECTLY."

# ---------------------------------------------------------------------------
# Enumerations
#
# Every closed set the manifest can contain is declared here so the validator,
# the classifier and the emitted TypeScript union types cannot drift apart.
# ---------------------------------------------------------------------------

INSTRUMENTS = (
    "SINGING_BOWL",
    "BELL",
    "CHIME",
    "TUNING_FORK",
    "KALIMBA",
    "TEXTURE",
    "DRONE",
    "AMBIENT",
    "UNKNOWN",
)

DURATION_CLASSES = ("MICRO", "SHORT", "MEDIUM", "LONG", "EXTENDED")

TONALITY = ("TONAL", "PARTIALLY_TONAL", "INHARMONIC", "ATONAL", "UNKNOWN")

ROLES = (
    "ACCENT",
    "TRANSITION",
    "DETAIL",
    "BELL_STRIKE",
    "CHIME_STRIKE",
    "FORK_EVENT",
    "FOREGROUND_GESTURE",
    "RESONANT_HIT",
    "PHRASE",
    "SECONDARY_LAYER",
    "PRIMARY_BOWL",
    "LONG_RESONANCE",
    "MAJOR_EVENT",
    "BED",
    "EXTENDED_TEXTURE",
    "LONG_PERFORMANCE",
)

CHARACTER_TAGS = (
    "deep", "warm", "bright", "airy", "dark", "gentle", "strong", "metallic",
    "shimmering", "smooth", "rough", "low", "mid", "high",
    "short_decay", "medium_decay", "long_decay",
    "tonal", "inharmonic", "percussive", "sustained",
)

PITCH_CLASSES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")

# Where a note came from. Two values and never a third: either the spectrum
# corroborated the pitch or the library's own filename supplied it. A consumer
# that cannot tell those apart is one that will present a vendor's label as a
# measurement (§18), so the distinction is a closed set rather than free text.
NOTE_SOURCES = ("measured", "filename")

# Formats libsndfile decodes without help. M4A/AAC need ffmpeg, which the
# pipeline treats as optional and reports as a warning rather than a failure.
NATIVE_EXTENSIONS = (".wav", ".wave", ".aif", ".aiff", ".aifc", ".flac", ".ogg", ".mp3", ".w64", ".caf")
FFMPEG_EXTENSIONS = (".m4a", ".aac", ".mp4")
SUPPORTED_EXTENSIONS = NATIVE_EXTENSIONS + FFMPEG_EXTENSIONS


@dataclass(frozen=True)
class DurationBand:
    """One duration class and the range that puts an asset in it.

    Bounds are seconds, lower-inclusive and upper-exclusive, so an asset of
    exactly 2.0 s lands in SHORT rather than in both or neither.
    """

    name: str
    min_seconds: float
    max_seconds: float | None


# §9's suggested defaults. Configurable: `config.py` can replace the table, and
# the exact duration is always stored alongside the class so no consumer is ever
# forced to work from the bucket alone.
DEFAULT_DURATION_BANDS: tuple[DurationBand, ...] = (
    DurationBand("MICRO", 0.0, 2.0),
    DurationBand("SHORT", 2.0, 6.0),
    DurationBand("MEDIUM", 6.0, 20.0),
    DurationBand("LONG", 20.0, 60.0),
    DurationBand("EXTENDED", 60.0, None),
)


def duration_class(seconds: float, bands: tuple[DurationBand, ...] = DEFAULT_DURATION_BANDS) -> str:
    for band in bands:
        if seconds >= band.min_seconds and (band.max_seconds is None or seconds < band.max_seconds):
            return band.name
    return bands[-1].name


# ---------------------------------------------------------------------------
# Record shape
# ---------------------------------------------------------------------------

# Every field, its JSON type, and whether it may be null. `None` in the type
# position means "any JSON value" and is used only for lists whose element shape
# is checked separately. This table drives both validation and TypeScript
# emission, so a field cannot be added to one without the other.
FIELD_SPEC: dict[str, dict[str, tuple[str, bool]]] = {
    "source": {
        "filename": ("string", False),
        "relativePath": ("string", False),
        "contentHash": ("string", False),
        "format": ("string", False),
        "bytes": ("integer", False),
    },
    "audio": {
        "durationSeconds": ("number", False),
        "sampleRate": ("integer", False),
        "channels": ("integer", False),
        "bitDepth": ("integer", True),
        "frameCount": ("integer", False),
    },
    "levels": {
        "peakDbFS": ("number", True),
        "truePeakDbFS": ("number", True),
        "rmsDbFS": ("number", True),
        "integratedLufs": ("number", True),
        "recommendedGainDb": ("number", True),
    },
    "timing": {
        "leadingSilenceSeconds": ("number", True),
        "trailingSilenceSeconds": ("number", True),
        "recommendedStartOffset": ("number", True),
        "recommendedEndOffset": ("number", True),
    },
    "spectral": {
        "fundamentalHz": ("number", True),
        "pitchConfidence": ("number", True),
        "note": ("string", True),
        "pitchClass": ("string", True),
        # What the *analysis* concluded about the note. `measured` means the
        # spectrum corroborated it; `filename` means the library labelled it and
        # the audio could neither confirm nor deny; null means the analysis
        # reached no conclusion at all.
        #
        # It stays null when a curator sets a pitch by hand, even though a note
        # is then present — this field records what the pipeline did, and
        # `review.manualOverride` records that a person intervened. Keeping them
        # separate is what lets a consumer ask the question it actually cares
        # about: retuning is applied only on `measured`, so a human's judgement
        # call and a vendor's label are both correctly left alone.
        "noteSource": ("string", True),
        "tonality": ("string", False),
        "spectralCentroidHz": ("number", True),
        "spectralRolloffHz": ("number", True),
        "brightness": ("number", True),
        "transientStrength": ("number", True),
        "decaySeconds": ("number", True),
    },
    "classification": {
        "instrument": ("string", False),
        "durationClass": ("string", False),
    },
    "runtime": {
        "streamingRecommended": ("boolean", False),
        "preloadRecommended": ("boolean", False),
        "loopable": ("boolean", False),
        "maxRecommendedVoices": ("integer", False),
    },
    "review": {
        "approved": ("boolean", False),
        "manualOverride": ("boolean", False),
        "notes": ("string", True),
    },
}

# Sections whose contents are lists rather than scalar fields.
LIST_FIELDS = {
    "classification": ("recommendedRoles", "characterTags"),
    "spectral": ("resonantPeaksHz",),
}


@dataclass(frozen=True)
class EnumBinding:
    """Ties one field to the closed set its values are drawn from.

    `FIELD_SPEC` can only say that `classification.instrument` holds a string.
    This table says *which* strings, which is what lets the validator reject an
    unknown instrument and lets the emitted TypeScript declare a union type
    rather than `string`. Both read this one table; a list kept by hand on
    either side would be the second schema §25 exists to prevent, and the side
    that drifts is always the one nobody is looking at.

    `message` is per field rather than generated, because it is read by a
    curator in a terminal (§51) and "which is not a note name" tells them more
    than a uniform sentence would.
    """

    section: str
    field: str
    values: tuple[str, ...]
    #: Name of the emitted TypeScript union type.
    ts_type: str
    #: Name of the emitted `as const` array the union is derived from.
    ts_const: str
    #: True when the field holds a list of these values rather than one of them.
    is_list: bool
    #: Whether an unknown value fails preprocessing or only warns (§27).
    fatal: bool
    message: str


ENUM_FIELDS: tuple[EnumBinding, ...] = (
    EnumBinding(
        "classification", "instrument", INSTRUMENTS,
        "OrganicInstrument", "ORGANIC_INSTRUMENTS", False, True,
        "has instrument {value!r}, which is not a known category.",
    ),
    EnumBinding(
        "classification", "durationClass", DURATION_CLASSES,
        "OrganicDurationClass", "ORGANIC_DURATION_CLASSES", False, True,
        "has duration class {value!r}, which is not known.",
    ),
    EnumBinding(
        "classification", "recommendedRoles", ROLES,
        "OrganicRole", "ORGANIC_ROLES", True, False,
        "has an unrecognised role {value!r}.",
    ),
    EnumBinding(
        "classification", "characterTags", CHARACTER_TAGS,
        "OrganicCharacterTag", "ORGANIC_CHARACTER_TAGS", True, False,
        "has an unrecognised tag {value!r}.",
    ),
    EnumBinding(
        "spectral", "tonality", TONALITY,
        "OrganicTonality", "ORGANIC_TONALITY", False, True,
        "has tonality {value!r}, which is not known.",
    ),
    EnumBinding(
        "spectral", "pitchClass", PITCH_CLASSES,
        "OrganicPitchClass", "ORGANIC_PITCH_CLASSES", False, True,
        "has pitch class {value!r}, which is not a note name.",
    ),
    EnumBinding(
        "spectral", "noteSource", NOTE_SOURCES,
        "OrganicNoteSource", "ORGANIC_NOTE_SOURCES", False, True,
        "has note source {value!r}; a note is either measured or read from the filename.",
    ),
)


@dataclass(frozen=True)
class ListElement:
    """The shape of one item in a list field that holds objects."""

    ts_type: str
    fields: dict[str, tuple[str, bool]]


# The lists in `LIST_FIELDS` that hold objects rather than enum values. Declared
# because `FIELD_SPEC` stops at the list itself: without this the validator
# would accept `[{"hz": "loud"}]` and the emitter would have no choice but to
# write `unknown[]` or have a person type the element out by hand.
LIST_ELEMENT_SPEC: dict[tuple[str, str], ListElement] = {
    ("spectral", "resonantPeaksHz"): ListElement(
        "OrganicResonantPeak",
        {"hz": ("number", False), "strength": ("number", False)},
    ),
}


# The envelope the asset list is written inside, in the order it is written.
# `manifest.build` assembles the file from these names, so a field that exists
# in the JSON and not here cannot happen: it would be dropped on the way out and
# noticed on the next run.
MANIFEST_FIELDS: tuple[tuple[str, str, str], ...] = (
    ("_comment", "string", "Why this file must never be hand-edited (§22)."),
    ("schemaVersion", "integer", "The record shape. Refuse a manifest whose version you do not know (§33)."),
    ("analysisVersion", "string", "What the measuring code did. Changes when a measured number would."),
    ("organicLibraryVersion", "string", "The content of the sample library, as a curatorial fact (§34)."),
    ("assetCount", "integer", "`assets.length`, carried so a truncated file is obvious."),
    ("counts", "counts", "The summary block; see the type."),
    ("assets", "assets", "Sorted by `assetId`, so two runs over the same library are byte-identical (§56)."),
)


@dataclass
class ValidationIssue:
    """One problem found by the validator.

    `fatal` decides whether preprocessing fails or merely warns (§27). The
    message is written for a person reading a terminal, not for a log parser
    (§51): it names the asset, the field and what would have to be true.
    """

    fatal: bool
    assetId: str | None
    message: str

    def render(self) -> str:
        where = f"{self.assetId}: " if self.assetId else ""
        return f"{'ERROR' if self.fatal else 'warning'}  {where}{self.message}"


@dataclass
class Asset:
    """One analysed asset, in the shape the manifest serialises."""

    assetId: str
    label: str
    source: dict[str, Any] = field(default_factory=dict)
    audio: dict[str, Any] = field(default_factory=dict)
    levels: dict[str, Any] = field(default_factory=dict)
    timing: dict[str, Any] = field(default_factory=dict)
    spectral: dict[str, Any] = field(default_factory=dict)
    classification: dict[str, Any] = field(default_factory=dict)
    runtime: dict[str, Any] = field(default_factory=dict)
    review: dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> dict[str, Any]:
        return {
            "assetId": self.assetId,
            "label": self.label,
            "source": self.source,
            "audio": self.audio,
            "levels": self.levels,
            "timing": self.timing,
            "spectral": self.spectral,
            "classification": self.classification,
            "runtime": self.runtime,
            "review": self.review,
        }
